### PR TITLE
Adding IRRCNN model

### PR DESCRIPTION
**Pull request by leoarc**
Adds another classification model. 

Most of the code is from the already present IRCNN model . This one contains residual connections which adds the inputs to the outputs of each IRCNN block. It is based on the [Inception_V4](https://arxiv.org/pdf/1602.07261.pdf) instead of the Inception_V3 .

This is more of a version update as :

- It uses the latest dataset [ICIAR'18](https://iciar2018-challenge.grand-challenge.org/Dataset/)

- It uses a improved version of the IRCNN model which is shown in the [paper](https://arxiv.org/pdf/1811.04241.pdf) as to work very well on the BACH dataset

The parameters chosen are from one of the experiments done in the above paper.
 
The accuracy levels are not as good as in the paper as I only trained on 1/3rd of the data and for only 20 epochs (150 in the paper) .( I'll try to train it more afterwards .)

I have tested the tfjs model in caMicroscope and its working. 

@Insiyaa  Do you think this is worth adding ?

### CODE REVIEW

**Comment by Insiyaa** [comment]
This is a good addition. If feasible, do train this further!
I already see the patch size in the readme, could you please add if the model is trained on RGB/b&w images and pre-processing used for those using the tfjs model directly?

**Comment by leoarc** [comment]
Done !

**Comment by Insiyaa** [comment]
Good! Please also add magnification.

**Comment by leoarc** [comment]
Sorry for not including everything at once . Anything else I've missed ?

**Review by Insiyaa — APPROVED** [review]
Looks complete! Thank you!

**Pull request merged**
